/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;
import static basiclibrary.Library.*;
public class LibraryTest {
    @Test 
    public void stestRollDice() {
        int[] res = roll(10);
        assertTrue("Roll Dice : ", res.length == 10);
    }

    @Test
    public void testContainsDups(){
        int[] arr = {1,2,3,3,4,5,6};
        assertTrue("contains Dups : ", containsDuplicates(arr));
    }

    @Test
    public void testDoesNotContainsDups(){
        int[] arr = {1,2,3,4,5,6};
        assertFalse("contains Dups : ", containsDuplicates(arr));
    }
   
    @Test public void Average(){
        int[] array = {1, 1, 1, 1};
        float average;
        average = Library.Average(array);
        assertEquals(1.0,average,1.0);
    }

    @Test public void TwoArrays() {
        int[][] array = {{1, 1, 1, 1}, {2, 2, 2, 2}, {3, 3, 3, 3}};
        float average = Library.TwoArrays(array);
        assertEquals(1.0, average, 1.0);
    }

   
}
