/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.Test;
import static org.junit.Assert.*;
import static basiclibrary.Library.*;
public class LibraryTest {
    @Test 
    public void stestRollDice() {
        int[] res = roll(10);
        assertTrue("Roll Dice : ", res.length == 10);
    }

    @Test
    public void testContainsDups(){
        int[] arr = {1,2,3,3,4,5,6};
        assertTrue("contains Dups : ", containsDuplicates(arr));
    }

    @Test
    public void testDoesNotContainsDups(){
        int[] arr = {1,2,3,4,5,6};
        assertFalse("contains Dups : ", containsDuplicates(arr));
    }
   
    @Test public void Average(){
        int[] array = {1, 1, 1, 1};
        float average;
        average = Library.Average(array);
        assertEquals(1.0,average,1.0);
    }

    @Test public void TwoArrays() {
        int[][] array = {{1, 1, 1, 1}, {2, 2, 2, 2}, {3, 3, 3, 3}};
        float average = Library.TwoArrays(array);
        assertEquals(1.0, average, 1.0);
    }
    @Test public void testanalyzeWeather() {
        int[][] array = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String output = Library.analyzeWeather(array);
        assertEquals("High: 70\nLow: 53\nNever saw temperature: 53\nNever saw temperature: 58\nNever saw temperature: 64\nNever saw temperature: 65\nNever saw temperature: 70\n", output);
    }

    @Test public void testTally() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String output = Library.tally(votes);
        System.out.println(output);
        assertEquals("Bush", output);
    }
   
}
