/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n){
        int[] rolls = new int[n];
        for(int i = 0; i < n; i++){
            rolls[i] =  (int)(Math.random() * (6 + 1));
        }
        return rolls;
    }

    public static boolean containsDuplicates(int[] arr){

        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length; j++) {
                if(arr[i] == arr[j] && i != j) return true;
            }
        }
        return false;
    }

    public static float Average (int[] array) {
        float total = 0;

        for (int i=0; i<array.length; i++){
            total = total + array[i];

        }

        return total/array.length;

    }
    
    public static float TwoArrays (int[][] array) {

        float[] averageArray = new float[array.length];
        for (int i=0; i<array.length; i++){
            averageArray[i] = Average(array[i]);
        }

        float low =averageArray[0];
        for (int i=0; i<averageArray.length; i++ ){
            if(averageArray[i]<low){
                low=averageArray[i];
            }
        }
        return low;


    }
}
